name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
    - name: push master
      run: |-
        git config --global user.name "davidsiaw(ghactions)"
        git config --global user.email "874280+davidsiaw@users.noreply.github.com"
        git config --global gpg.format ssh
        git config --global commit.gpgsign true
        echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvy8tiGuleRqem2Ssfk3UX1DhwZizanrfpP5cjTIHnz davidsiaw@debiddonoMacBook-Pro-2.local" > signingkey
        git config --global user.signingkey $PWD/signingkey
        sh deploy.sh

'on':
  push:
    branches:
    - '*'